apiVersion: v1
kind: Service
metadata:
  name: owncloud
  namespace: owncloud
spec:
  # Use ClusterIP for internal service; expose externally via an OpenShift Route
  type: ClusterIP
  selector:
    app: owncloud
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort removed; Route will be used to expose the service instead
